version: '3'
services:
  auditlimit:
    image: xyhelper/auditlimit
    restart: always
    ports:
      - "127.0.0.1:9655:8777"
    volumes:
      - ./data:/app/data
    environment:
      LIMIT: 80  # 限制每个userToken允许的次数
      PER: "5h" # 限制周期 1s, 1m, 1h, 1d, 1w, 1y
      O1LIMIT: 10  # 限制每个userToken允许的O1模型次数
      O1PER: "1w" # 限制周期 1s, 1m, 1h, 1d, 1w, 1y

    


    